// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rKjDbS00gko_FPfSrjtJvXWbD51GHaQ',
    appId: '1:905282232875:web:1039dac1a12a9cc294806e',
    messagingSenderId: '905282232875',
    projectId: 'fir-flutter-codelab-51bea',
    authDomain: 'fir-flutter-codelab-51bea.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-51bea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY1K8tk5dv36bn_vYJ-b09dre35ZQ641g',
    appId: '1:905282232875:android:edb92481945523b794806e',
    messagingSenderId: '905282232875',
    projectId: 'fir-flutter-codelab-51bea',
    storageBucket: 'fir-flutter-codelab-51bea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtBPIj1PDK6pf3dtkJov6egYWSsz8ixNo',
    appId: '1:905282232875:ios:0044f32252b49e7a94806e',
    messagingSenderId: '905282232875',
    projectId: 'fir-flutter-codelab-51bea',
    storageBucket: 'fir-flutter-codelab-51bea.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtBPIj1PDK6pf3dtkJov6egYWSsz8ixNo',
    appId: '1:905282232875:ios:0044f32252b49e7a94806e',
    messagingSenderId: '905282232875',
    projectId: 'fir-flutter-codelab-51bea',
    storageBucket: 'fir-flutter-codelab-51bea.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
